# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('blog', '0003_biopage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biopage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='biopage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='BioPage',
        ),
    ]
