# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 01:43
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_subequipepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subequipepage',
            name='name1',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subequipepage',
            name='name2',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subequipepage',
            name='name3',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subequipepage',
            name='name4',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
