# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 01:45
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20170123_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subequipepage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
