# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20170123_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subequipepage',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='subequipepage',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='subequipepage',
            name='name3',
        ),
        migrations.RemoveField(
            model_name='subequipepage',
            name='name4',
        ),
    ]
