# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 04:05
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20170124_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biopage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
