# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_agendapage_mapa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendapage',
            name='mapa',
        ),
    ]
