# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20170125_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendapage',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
