# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('home', '0022_auto_20170125_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendaindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='agendapage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='agendapage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='AgendaIndexPage',
        ),
        migrations.DeleteModel(
            name='AgendaPage',
        ),
    ]
