# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20170127_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='url1',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='url2',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='url3',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='url4',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='url5',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='url6',
            field=models.URLField(blank=True),
        ),
    ]
